### PR TITLE
[WIP]: Added new rainbow kit version with its depedencies

### LINKED ISSUE #1011: Upgrade RainbowKit to v1.0.0

### PR DESCRIPTION
**Pull request by kkatusic**
resolve #1011

### CODE REVIEW

**Review by kristoferlund — APPROVED** [review]
Looks good! Merging

**Comment by kkatusic** [comment]
@kristoferlund how you solved build errors?

**Comment by kristoferlund** [comment]
I checked out main branch.
Deleted .yarn/cache folder
Pushed change
Checked out your branch
Updated with main
Run yarn
done

**Comment by kkatusic** [comment]
Why I always stuck :(

**Pull request merged**
