### PR TITLE
fix: resolved the typo in db migration description text

### PR DESCRIPTION
**Pull request by maniyuvan**
Issue [#820](https://github.com/givepraise/praise/issues/820)

Resolved the typo by taking a branch from api2.

### CODE REVIEW

**Review by kristoferlund — CHANGES_REQUESTED** [review]
A new migration has to be added. Old migrations will not be re-run once finished.

**Comment by kristoferlund** [comment]
Yes, please make PR to merge with branch api2 as all development is ongoing there. Soon we will merge all back to main and continue development there.

**Review by kristoferlund — CHANGES_REQUESTED** [review]
* Change to api branch can be removed completely, we are not updating api any longer.
* When doing database migrations you should not modify old migrations as they only run once. Migration 01 ran a long time ago and will not run again on existing systems. Instead, you should allways  create a new migration, in your case named `32_xxx`.

**Comment by maniyuvan** [comment]
Okay, I'll close this PR and create a new one with new migration file for api2 alone as you said.

**Pull request closed without merging**
