### PR TITLE
Fix date format for end date to match start date

### PR DESCRIPTION
**Pull request by ujwalkumar1995**
Hey @kristoferlund 
This PR is for the issue #1021 
Let me know in case any changes are required.

### CODE REVIEW

**Review by kristoferlund — CHANGES_REQUESTED** [review]
Thanks for the quick fix. The period end date is not shown only there though. Look a few lines below and you will see `<PeriodDateForm />` where date also is shown. Rule is like this: 

- If user is regular user, display date in div
- If user is admin, display a date input allowing the admin to change date

**Comment by ujwalkumar1995** [comment]
Hey @kristoferlund 
Thank you for the feedback. I assume you want me to try and set a format on the input of the date.. I did some research and as per below docs it says 

> Note: The displayed date format will differ from the actual value — the displayed date is formatted based on the locale of the user's browser, but the parsed value is always formatted yyyy-mm-dd.

Also mentioning the link for your reference.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date

Could you please let me know if I am missing something here?

**Comment by kristoferlund** [comment]
@ujwalkumar1995, the displayed date should be formatted yyyy-mm-dd, the parsed value we don't need to touch, but maybe that is not achievable with the default date input?

**Comment by ujwalkumar1995** [comment]
Hi @kristoferlund 
Yes that is at least what I could understand from my research. The display date in input takes the format from browser depending on user's locale.

**Comment by kristoferlund** [comment]
@ujwalkumar1995 Thank you for looking into this! I will be merging your PR. We would like to solve this issue eventually, using another date component or some small trick to achieve desired result with the default input. If you would like to take this on, feel free. In any case, thanks for your contribution so far!

**Review by kristoferlund — APPROVED** [review]
Looks good! Merging.

**Pull request merged**
