### PR TITLE
feat: first praise -> activate

### LINKED ISSUE #1048: Activate account when praising the first time
We want to make it easier for users to activate. Instead of requiring a separate activation step, allow for activating the first time you praise as well.

1. User tries to praise
2. API: User has not activated their account
3. Notify user with activation message: 
  - not yet activated
  - click here to activate
  - retry button
  - When done activating click retry button
4. User clicks retry after activating
5. Praise sent

### PR DESCRIPTION
**Pull request by Vyvy-vi**
fixes #1048

### CODE REVIEW

**Review by kristoferlund — DISMISSED** [review]
Flow worked great!

If pressing retry before account has been activated, the bot gives you a confirmation as if command had completed and the crashes.

image

And, I think it is ok to have a timeout on the retry button as long as user is notified in a good way.

**Review by kristoferlund — CHANGES_REQUESTED** [review]
Retry message was sent twice when I reviewed this.

image

1. Try praising
2. Bot says: "In order to dish.. "
3. I click "RETRY", bot answers with "Retry failed"
4. I go to website and activate
5. I click "RETRY" again
6. Praise is sent.. and "Retry failed" message is printed again.

**Comment by Vyvy-vi** [comment]
@kristoferlund I've made the needed changes.

**Review by kristoferlund — APPROVED** [review]
Nice, this will greatly simplify the onboarding process.

**Pull request merged**
