### PR TITLE
Fix Github actions jobs

### PR DESCRIPTION
**Pull request by mohammadranjbarz**
related #892

### CODE REVIEW

**Comment by mohammadranjbarz** [comment]
* Remove running tests in api workflow to not block other steps like build/push docker image
* Fix lots of lint errors in discord-bot most of them was related to imports

@kristoferlund  There were something that I didn't know how should I fix them for example how to get new instance SettingService to use it as settingValue ??

**Comment by kristoferlund** [comment]
@mohammadranjbarz 

I think we can remove this check for now from the github action.

image

The unit tests are really not up to date as we have been focusing on e2e tests instead.

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz
> 
> I think we can remove this check for now from the github action.
> 
> image
> 
> The unit tests are really not up to date as we have been focusing on e2e tests instead.

Ok, thanks for letting me know

**Comment by mohammadranjbarz** [comment]
@kristoferlund I deleted the 
```
     - run: echo "${{secrets.ROOT_ENV_TESTING }}" > .env
      - run: echo "${{secrets.API_ENV_TESTING }}" > packages/api2/.env
      - run: echo "${{secrets.DISCORDBOT_ENV_TESTING }}" > packages/discord-bot/.env
      - run: echo "${{secrets.FRONTEND_ENV_TESTING }}" > packages/frontend/.env
```
stuff, I think it's better and simpler to just copy `.env.template` to `.env`, so I filled values of variables in `.env.template` and we don't need to pass those values in secrets anymore, but if you think it's not clean to fill values of `.env.template` we can create a `.env.test` and use them in `CI/CD` like I did before on impact-graph project https://github.com/Giveth/impact-graph/blob/staging/config/test.env

WDYT?

**Comment by kristoferlund** [comment]
@mohammadranjbarz I think it is better to use a separate `.env.test`. The values specified in `.env.template` are used as defaults when running the setup script.

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz I think it is better to use a separate `.env.test`. The values specified in `.env.template` are used as defaults when running the setup script.

@kristoferlund  Done.

**Review by kristoferlund — APPROVED** [review]
👍👍👍

**Pull request merged**
